all:
  - Symfony\Bundle\FrameworkBundle\FrameworkBundle
#  - Symfony\Bundle\Sensio\FrameworkExtraBundle\FrameworkExtraBundle
  - Symfony\Bundle\TwigBundle\TwigBundle
  - Symfony\Bundle\ZendBundle\ZendBundle
  - Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
#  - Symfony\Bundle\AsseticBundle\AsseticBundle
#- Symfony\Bundle\DoctrineMigrationsBundle\DoctrineMigrationsBundle
#- Symfony\Bundle\DoctrineMongoDBBundle\DoctrineMongoDBBundle
#  - rs\ProjectUtilitiesBundle\ProjectUtilitiesBundle
  - rs\kaoz4Bundle\kaoz4Bundle
#  - Sonata\NewsBundle\SonataNewsBundle
  - Knplabs\MenuBundle\KnplabsMenuBundle
  
dev:
  - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
  
test:
  