all:
  - Symfony\Bundle\FrameworkBundle\FrameworkBundle
  - Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle
  - Symfony\Bundle\TwigBundle\TwigBundle
  - Symfony\Bundle\ZendBundle\ZendBundle
  - Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
#  - Symfony\Bundle\DoctrineAbstractBundle\DoctrineAbstractBundle
  - Symfony\Bundle\DoctrineBundle\DoctrineBundle  
#  - Symfony\Bundle\AsseticBundle\AsseticBundle
  - Symfony\Bundle\DoctrineMigrationsBundle\DoctrineMigrationsBundle
#  - Symfony\Bundle\DoctrineMongoDBBundle\DoctrineMongoDBBundle
#  - rs\ProjectUtilitiesBundle\ProjectUtilitiesBundle

  - rs\kaoz4Bundle\kaoz4Bundle
#  - Sonata\NewsBundle\SonataNewsBundle
  - Knplabs\MenuBundle\KnplabsMenuBundle
  - Bundle\BlogBundle\BlogBundle
  
dev:
  - Symfony\Bundle\WebProfilerBundle\WebProfilerBundle
  
test:
  