homepage:
    pattern:  /
    defaults: { _controller: kaoz4:Home:index }

blog:
    resource: '@Blog/Resources/config/routing.yml'

#news:
#    resource: '@SonataNews/Resources/config/routing/news.xml'
#    prefix:   /news  