_main:
    resource: routing.yml

_profiler:
    resource: '@WebProfiler/Resources/config/routing/profiler.xml'
    prefix:   /_profiler
    
_wdt:
    resource: '@WebProfiler/Resources/config/routing/wdt.xml'
    prefix:   /_wdt
