imports:
    - { resource: config.yml }

framework:
    error_handler: false
    test: ~

#web_profiler:
#    toolbar: false
#    intercept_redirects: false

#project_utilities: ~

#monolog:
#    logger:
#        priority: debug
#        path:     %kernel.logs_dir%/%kernel.environment%.log
