security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

#    role_hierarchy:
#        ROLE_ADMIN: ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                user: { password: admin, roles: [ 'ROLE_USER' ] }
                admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
      
        dashboard:
            pattern: /dashboard.*
            http_basic: true

        admin:
            pattern: /admin/.*
            http_basic: true
            
        public:
            pattern:  /.*
            security: false      
            
        profiler:
            pattern: ^/_profiler
            security: false

        wdt:
            pattern: ^/_wdt
            security: false


    access_control:
#        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}        
        - { path: /dashboard.*, role: ROLE_ADMIN }
        - { path: /admin/.*, role: ROLE_ADMIN  } #, requires_channel: https
