post_admin_create:
    pattern:  post/create
    defaults: { _controller: kaoz4Bundle:PostAdmin:create, _sonata_admin: kaoz4.admin.post }    
post_admin_list:
    pattern:  post
    defaults: { _controller: kaoz4Bundle:PostAdmin:list, _sonata_admin: kaoz4.admin.post }
post_admin_batch:
    pattern:  post/batch
    defaults: { _controller: kaoz4Bundle:PostAdmin:batch, _sonata_admin: kaoz4.admin.post }
post_admin_edit:
    pattern:  post/edit/{id}
    defaults: { _controller: kaoz4Bundle:PostAdmin:edit, _sonata_admin: kaoz4.admin.post }
post_admin_comments:
    pattern:  comments
    defaults: { _controller: kaoz4Bundle:CommentAdmin:list, _sonata_admin: kaoz4.admin.comment }

news_admin_create:
    pattern:  news/create
    defaults: { _controller: kaoz4Bundle:NewsAdmin:create, _sonata_admin: kaoz4.admin.news }    
news_admin_list:
    pattern:  news
    defaults: { _controller: kaoz4Bundle:NewsAdmin:list, _sonata_admin: kaoz4.admin.news }
news_admin_batch:
    pattern:  news/batch
    defaults: { _controller: kaoz4Bundle:NewsAdmin:batch, _sonata_admin: kaoz4.admin.news }
news_admin_edit:
    pattern:  news/edit/{id}
    defaults: { _controller: kaoz4Bundle:NewsAdmin:edit, _sonata_admin: kaoz4.admin.news }
news_admin_comments:
    pattern:  comments
    defaults: { _controller: kaoz4Bundle:CommentAdmin:list, _sonata_admin: kaoz4.admin.comment }

contribution_admin_create:
    pattern:  contribution/create
    defaults: { _controller: kaoz4Bundle:ContributionAdmin:create, _sonata_admin: kaoz4.admin.contribution }    
contribution_admin_list:
    pattern:  contribution
    defaults: { _controller: kaoz4Bundle:ContributionAdmin:list, _sonata_admin: kaoz4.admin.contribution }
contribution_admin_batch:
    pattern:  contribution/batch
    defaults: { _controller: kaoz4Bundle:ContributionAdmin:batch, _sonata_admin: kaoz4.admin.contribution }
contribution_admin_edit:
    pattern:  contribution/edit/{id}
    defaults: { _controller: kaoz4Bundle:ContributionAdmin:edit, _sonata_admin: kaoz4.admin.contribution }
contribution_admin_comments:
    pattern:  comments
    defaults: { _controller: kaoz4Bundle:CommentAdmin:list, _sonata_admin: kaoz4.admin.comment }
    
tag_admin_create:
    pattern:  tags/create
    defaults: { _controller: kaoz4Bundle:TagAdmin:create, _sonata_admin: kaoz4.admin.tag }    
tag_admin_list:
    pattern:  tags
    defaults: { _controller: kaoz4Bundle:TagAdmin:list, _sonata_admin: kaoz4.admin.tag }
tag_admin_batch:
    pattern:  tags/batch
    defaults: { _controller: kaoz4Bundle:TagAdmin:batch, _sonata_admin: kaoz4.admin.tag }
tag_admin_edit:
    pattern:  tags/edit/{id}
    defaults: { _controller: kaoz4Bundle:TagAdmin:edit, _sonata_admin: kaoz4.admin.tag }    

comment_admin_create:
    pattern:  comments/create
    defaults: { _controller: kaoz4Bundle:CommentAdmin:create, _sonata_admin: kaoz4.admin.comment }    
comment_admin_list:
    pattern:  comments
    defaults: { _controller: kaoz4Bundle:CommentAdmin:list, _sonata_admin: kaoz4.admin.comment }
comment_admin_batch:
    pattern:  comments/batch
    defaults: { _controller: kaoz4Bundle:CommentAdmin:batch, _sonata_admin: kaoz4.admin.comment }
comment_admin_edit:
    pattern:  comments/edit/{id}
    defaults: { _controller: kaoz4Bundle:CommentAdmin:edit, _sonata_admin: kaoz4.admin.comment }        
    
user_admin_create:
    pattern:  users/create
    defaults: { _controller: kaoz4Bundle:UserAdmin:create, _sonata_admin: kaoz4.admin.user }    
user_admin_list:
    pattern:  users
    defaults: { _controller: kaoz4Bundle:UserAdmin:list, _sonata_admin: kaoz4.admin.user }
user_admin_batch:
    pattern:  users/batch
    defaults: { _controller: kaoz4Bundle:UserAdmin:batch, _sonata_admin: kaoz4.admin.user }
user_admin_edit:
    pattern:  users/edit/{id}
    defaults: { _controller: kaoz4Bundle:UserAdmin:edit, _sonata_admin: kaoz4.admin.user }            