blog:
    pattern:  /
    defaults: { _controller: kaoz4Bundle:Blog:archive }    

blog_latest:
    pattern:  /latest
    defaults: { _controller: kaoz4Bundle:Blog:latest }    

blog_view:
    pattern:  /{slug}
    defaults: { _controller: kaoz4Bundle:Blog:view }    
